/* MAP-VOTE-EXTENDED EVENTS */
const START_VOTE = 'VM_EXTENDED_START_VOTE';

const END_VOTE = 'VM_EXTENDED_END_VOTE';

const NOMINATION_START = 'VM_EXTENDED_NOMINATION_START';

/* RCON ACTIONS */
// const RCON_

// const CHATS_CHATALL = "ChatAll"

export { START_VOTE, END_VOTE, NOMINATION_START };
