/* MAP-VOTE-EXTENDED EVENTS */
const START_VOTE = 'VM_EXTENDED_START_VOTE';

const END_VOTE = 'VM_EXTENDED_END_VOTE';

const NOMINATION_START = 'VM_EXTENDED_NOMINATION_START';

const NOMINATION_TRIGGER_CREATED = 'VM_EXTENDED_NOMINATION_TRIGGER_CREATED';

const START_NEW_MAP = 'VM_EXTENTED_START_NEW_MAP';

const NOMINATION_FETCH = 'VM_EXTENDED_NOMINATION_FETCH';

const FINAL_MAP_FETCH = 'VM_EXTENDED_MAP_FETCH';

const TRIGGER_START_VOTE = 'VM_TRIGGER_START_VOTE';

/* RCON ACTIONS */
// const RCON_

// const CHATS_CHATALL = "ChatAll"

export {
  START_VOTE,
  NOMINATION_START,
  START_NEW_MAP,
  NOMINATION_FETCH,
  FINAL_MAP_FETCH,
  TRIGGER_START_VOTE,
  END_VOTE,
  NOMINATION_TRIGGER_CREATED
};
