const START_VOTE = 'VM_EXTENDED_START_VOTE';

const END_VOTE = 'VM_EXTENDED_END_VOTE';

const NOMINATION_START = 'VM_EXTENDED_NOMINATION_START';

const NOMINATION_TRIGGER_CREATED = 'VM_EXTENDED_NOMINATION_TRIGGER_CREATED';

const START_NEW_MAP = 'VM_EXTENTED_START_NEW_MAP';

const NOMINATION_FETCH = 'VM_EXTENDED_NOMINATION_FETCH';

const FINAL_MAP_FETCH = 'VM_EXTENDED_MAP_FETCH';

const TRIGGER_START_VOTE = 'VM_TRIGGER_START_VOTE';

const PLUGIN_STATE_SWITCH = 'VM_PLUGIN_STATE_SWITCH';

const MAPVOTE_FILTERS_ALLOW_ONLY_LAYERS = 'ALLOW ONLY LAYERS';

const MAPVOTE_FILTERS_BLOCK_MODE = 'BLOCK MODE';

const MAPVOTE_FILTERS_DECREASE_MODE = 'DECREASE MODE';

const MAPVOTE_FILTERS_DEDUPLICATE_MAP = 'DEDUPLICATE MAP';

const MAPVOTE_FILTERS_DECREASE_DLC = 'DECREASE DLC';

export {
  START_VOTE,
  NOMINATION_START,
  START_NEW_MAP,
  NOMINATION_FETCH,
  FINAL_MAP_FETCH,
  TRIGGER_START_VOTE,
  END_VOTE,
  NOMINATION_TRIGGER_CREATED,
  PLUGIN_STATE_SWITCH,
  MAPVOTE_FILTERS_ALLOW_ONLY_LAYERS,
  MAPVOTE_FILTERS_BLOCK_MODE,
  MAPVOTE_FILTERS_DECREASE_MODE,
  MAPVOTE_FILTERS_DEDUPLICATE_MAP,
  MAPVOTE_FILTERS_DECREASE_DLC
};
